"""empty message

Revision ID: 0d00beb3adfb
Revises: e2f661f07cdb
Create Date: 2022-06-17 00:20:42.950833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d00beb3adfb'
down_revision = 'e2f661f07cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson1_vocab_word_key', 'lesson1_vocab', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lesson1_vocab_word_key', 'lesson1_vocab', ['word'])
    # ### end Alembic commands ###
