"""empty message

Revision ID: 1dd4b34dbe31
Revises: 8c8f2493f2aa
Create Date: 2022-06-30 15:36:17.855228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd4b34dbe31'
down_revision = '8c8f2493f2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('lessons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'lessons')
    # ### end Alembic commands ###
