"""empty message

Revision ID: 4d0d41d9b53a
Revises: 8b9bd4293ff5
Create Date: 2022-06-16 23:43:46.223197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0d41d9b53a'
down_revision = '8b9bd4293ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adjacency_relation_node_id_parent_fkey', 'adjacency_relation', type_='foreignkey')
    op.drop_constraint('adjacency_relation_node_id_child_fkey', 'adjacency_relation', type_='foreignkey')
    op.create_foreign_key(None, 'adjacency_relation', 'lesson1_vocab', ['node_id_parent'], ['id'])
    op.create_foreign_key(None, 'adjacency_relation', 'lesson1_vocab', ['node_id_child'], ['id'])
    op.alter_column('lesson1_vocab', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('lesson1_vocab', 'part_of_speech',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson1_vocab', 'part_of_speech',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('lesson1_vocab', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint(None, 'adjacency_relation', type_='foreignkey')
    op.drop_constraint(None, 'adjacency_relation', type_='foreignkey')
    op.create_foreign_key('adjacency_relation_node_id_child_fkey', 'adjacency_relation', 'lesson', ['node_id_child'], ['id'])
    op.create_foreign_key('adjacency_relation_node_id_parent_fkey', 'adjacency_relation', 'lesson', ['node_id_parent'], ['id'])
    # ### end Alembic commands ###
