"""empty message

Revision ID: 6386329f45be
Revises: 097c8802d0fc
Create Date: 2022-06-30 02:43:57.340904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6386329f45be'
down_revision = '097c8802d0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
