"""empty message

Revision ID: 7e29f62e2543
Revises: 4d0d41d9b53a
Create Date: 2022-06-16 23:47:15.933118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e29f62e2543'
down_revision = '4d0d41d9b53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson1_vocab_images_key', 'lesson1_vocab', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lesson1_vocab_images_key', 'lesson1_vocab', ['images'])
    # ### end Alembic commands ###
