"""empty message

Revision ID: 8b9bd4293ff5
Revises: b2336e75b7b0
Create Date: 2022-06-16 23:18:47.154252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9bd4293ff5'
down_revision = 'b2336e75b7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson1_vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('phonetic', sa.String(length=50), nullable=False),
    sa.Column('mandarin', sa.String(length=150), nullable=False),
    sa.Column('phoneticM', sa.String(length=150), nullable=False),
    sa.Column('images', sa.String(length=500), nullable=False),
    sa.Column('part_of_speech', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('images'),
    sa.UniqueConstraint('mandarin'),
    sa.UniqueConstraint('phonetic'),
    sa.UniqueConstraint('phoneticM'),
    sa.UniqueConstraint('word')
    )
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phonetic', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mandarin', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phoneticM', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='words_pkey'),
    sa.UniqueConstraint('mandarin', name='words_mandarin_key'),
    sa.UniqueConstraint('phonetic', name='words_phonetic_key'),
    sa.UniqueConstraint('phoneticM', name='words_phoneticM_key'),
    sa.UniqueConstraint('word', name='words_word_key')
    )
    op.drop_table('lesson1_vocab')
    # ### end Alembic commands ###
