"""empty message

Revision ID: b2336e75b7b0
Revises: 7a79240d83f3
Create Date: 2022-06-15 15:23:47.453580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2336e75b7b0'
down_revision = '7a79240d83f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
