"""empty message

Revision ID: b44bab54459f
Revises: 0d00beb3adfb
Create Date: 2022-06-21 22:28:50.944148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bab54459f'
down_revision = '0d00beb3adfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=275), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=275), autoincrement=False, nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
