"""empty message

Revision ID: bc8928b525b4
Revises: 
Create Date: 2022-07-09 15:13:37.665782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8928b525b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson1_vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('mandarin', sa.String(length=150), nullable=False),
    sa.Column('phonetic', sa.String(length=50), nullable=False),
    sa.Column('phoneticM', sa.String(length=150), nullable=False),
    sa.Column('images', sa.String(length=500), nullable=True),
    sa.Column('part_of_speech', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_para',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_para', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=256), nullable=True),
    sa.Column('audio', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(length=275), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjacency_relation',
    sa.Column('node_id_parent', sa.Integer(), nullable=True),
    sa.Column('node_id_child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id_child'], ['lesson1_vocab.id'], ),
    sa.ForeignKeyConstraint(['node_id_parent'], ['lesson1_vocab.id'], )
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lessons', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=256), nullable=True),
    sa.Column('lesson_para', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('adjacency_relation')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('options')
    op.drop_table('lesson_para')
    op.drop_table('lesson1_vocab')
    op.drop_table('lesson')
    op.drop_table('favorites')
    # ### end Alembic commands ###
