"""empty message

Revision ID: cccc15b6241d
Revises: 7e29f62e2543
Create Date: 2022-06-16 23:52:43.350168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccc15b6241d'
down_revision = '7e29f62e2543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson1_vocab_mandarin_key', 'lesson1_vocab', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lesson1_vocab_mandarin_key', 'lesson1_vocab', ['mandarin'])
    # ### end Alembic commands ###
