"""empty message

Revision ID: e2f661f07cdb
Revises: cccc15b6241d
Create Date: 2022-06-17 00:08:19.670532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f661f07cdb'
down_revision = 'cccc15b6241d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson1_vocab_phoneticM_key', 'lesson1_vocab', type_='unique')
    op.drop_constraint('lesson1_vocab_phonetic_key', 'lesson1_vocab', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lesson1_vocab_phonetic_key', 'lesson1_vocab', ['phonetic'])
    op.create_unique_constraint('lesson1_vocab_phoneticM_key', 'lesson1_vocab', ['phoneticM'])
    # ### end Alembic commands ###
